### ISSUE TITLE
Attribute has no 'connect_request_ip'

### ISSUE THREAD

**Issue by marshallr1** [bashclub/check-unifi-controller#13]
Agent exited with code 1: Traceback (most recent call last):
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 652, in <module>
_controller = unifi_controller(_API=_api)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 182, in __init__
self._init()
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 437, in _init
self._get_sites()
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 467, in _get_sites
self._UNIFI_SITES.append(unifi_site(_PARENT=self,**_site))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 182, in __init__
self._init()
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 398, in _init
self._get_devices()
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 414, in _get_devices
self._UNIFICONTROLLER._UNIFI_DEVICES.append(unifi_device(_PARENT=self,**_device))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 182, in __init__
self._init()
File "/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 297, in _init
self.ip = self.connect_request_ip
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'unifi_device' object has no attribute 'connect_request_ip'

**Comment by an0key** [comment]
Upgraded a UDMP this evening to early access 4.2.4 and then hit this exact issue.... hadn't previously at all
