### ISSUE TITLE
Get output when runnin from host but no agent output

### ISSUE THREAD

**Issue by yuljk** [bashclub/check-unifi-controller#16]
Hi - I've installed the mkp and enabled it on my host.  If I run 

./agent_unifi_controller -u myunifiadmin -p somepass --ignore-cert --piggyback
mycontrollerurl:8443

I get output regarding my SSID's etc - so all looks good.

If I go to Setup > Other integrations > Unifi Controller via API and setup my controller details and then run a discovery on the monitored host I just get an error regarding agent_unifi_controller and no data output.

I should note that I am monitoring vCenter with piggback data enabled - not sure if that is causing any issues.

Also - Do I need to place anything in my plugins folder on the monitored host for this to work? - I copied agent_unifi_controller and chmod 755, but that didn't help.

Not quite sure where I'm going wrong here, any help would be much appreciated!

Running Checkmk Raw Edition 2.2.0p12

**Comment by thetravellor** [comment]
`Hey` yuljk I am trying to get to wor also, no luck here either.

May I ask how did you get the script to even run? 

I did su to my OMD user and ran the script and got

```
OMD[monitoring]:~$ ./local/share/check_mk/checks/agent_unifi_controller
-bash: ./local/share/check_mk/checks/agent_unifi_controller: Permission denied
OMD[monitoring]:~$

OMD[monitoring]:~$ python3 ./local/share/check_mk/checks/agent_unifi_controller
Traceback (most recent call last):
  File "/opt/omd/sites/monitoring/./local/share/check_mk/checks/agent_unifi_controller", line 45, in <module>
    special_agent_info['unifi_controller'] = agent_unifi_controller_arguments
    ^^^^^^^^^^^^^^^^^^
NameError: name 'special_agent_info' is not defined
OMD[monitoring]:~$

```
Im kinda lost

**Comment by yuljk** [comment]
Hi @thetravellor, what are the permissions of the agent_unifi_controller script? - It should be executable

**Comment by thetravellor** [comment]
I have validated the execute bit, I was running the wrong script from the CLI.

However, it still doesn't work, it cannot authenticate to the Unifi controller.

I have tried it with the admin use I use on a daily basis and a throw-away view only account that I am showing below.

```
OMD[monitoring]:~$ /opt/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller -u unpoller -p "Unpollerunpoller1" -s home --port 443 --ignore-cert cloudkey
<<<check_mk>>>
Version: 0.87
Traceback (most recent call last):
  File "/opt/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 641, in <module>
    _api = unifi_controller_api(**args.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 551, in __init__
    self.login(username,password)
  File "/opt/omd/sites/monitoring/local/share/check_mk/agents/special/agent_unifi_controller", line 585, in login
    raise unifi_api_exception("Login failed")
unifi_api_exception: Login failed
OMD[monitoring]:~$
```

Ive tried with the IP address, with --rawapi and without.....

Need the developers help here....

<img width="1464" alt="Screenshot 2023-11-03 at 10 08 57 am" src="https://github.com/bashclub/check-unifi-controller/assets/477905/1d35b5bb-e014-4cb4-a5cf-d9f28cc23855">

**Comment by thetravellor** [comment]
Hi yuljk, I found an "additional" unifi controller integration that you can install in parallel (https://gitlab.com/checkmk-extensions/unifi)

Keep this one installed, but remove the rules associated with it
Install the new agent MKP and create a rule for it. I had to enable UDM Pro even though I am using a UCK Gen 2 for it to work. I also had to create a site in the UCK, as this script needs one to work properly.

I am now correctly getting piggyback data for my Unifi devices

**Comment by thetravellor** [comment]
<img width="1291" alt="Screenshot 2023-11-03 at 10 53 33 am" src="https://github.com/bashclub/check-unifi-controller/assets/477905/9c24873a-417a-4d60-bf4e-c822fb8af239">


<img width="1001" alt="Screenshot 2023-11-03 at 10 55 17 am" src="https://github.com/bashclub/check-unifi-controller/assets/477905/f92642b8-a835-485e-958d-f5cd6ce5b10a">
<img width="1202" alt="Screenshot 2023-11-03 at 10 56 20 am" src="https://github.com/bashclub/check-unifi-controller/assets/477905/05e1e2f8-9537-46e8-82a1-f8968e7f755b">
